Language.py: Remove 'codeset' argument from gettext.install() call To fix runtime error.
[setIoPrio] best-effort level 3 ok
Traceback (most recent call last):
  File '/usr/lib/enigma2/python/StartEnigma.py', line 19, in <module>
    import Components.SetupDevices
  File '/usr/lib/enigma2/python/Components/SetupDevices.py', line 1, in <module>
  File '/usr/lib/enigma2/python/Components/config.py', line 7, in <module>
  File '/usr/lib/enigma2/python/Tools/NumericalTextInput.py', line 3, in <module>
  File '/usr/lib/enigma2/python/Components/Language.py', line 136, in <module>
  File '/usr/lib/enigma2/python/Components/Language.py', line 11, in __init__
TypeError: install() got an unexpected keyword argument 'codeset'

Changed in version 3.11: codeset parameter is removed
https://docs.python.org/3/library/gettext.html
Thanks to @Hains